### ISSUE TITLE
这个weibo_id是什么

### ISSUE THREAD

**Issue by Soarniner** [felinae98/prts-forward-bot#1]
PS C:\Users\Administrator\Downloads\prts-forward-bot-main\prts-forward-bot-main> nb run
02-26 20:55:47 [INFO] nonebot | NoneBot is initializing...
02-26 20:55:47 [INFO] nonebot | Current Env: prod
02-26 20:55:47 [INFO] nonebot | Succeeded to import "nonebot.plugins.echo"
02-26 20:55:47 [ERROR] nonebot | Failed to import "weibo_push"
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __c
all__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in mai
n
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in in
voke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in in
voke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in inv
oke
    return callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nb_cli\__init__.py", line 46, in
 run
    run_bot(file, app)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nb_cli\handlers.py", line 44, in
 run_bot
    module = importlib.import_module(module_name)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File ".\bot.py", line 26, in <module>
    nonebot.load_plugins("prts/plugins")
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin.py", line 1044, i
n load_plugins
    result = context.run(_load_plugin, module_info)
> File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\nonebot\plugin.py", line 1028, i
n _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "prts/plugins\weibo_push\__init__.py", line 5, in <module>
    plugin_config = Config(**global_config.dict())
  File "pydantic\env_settings.py", line 34, in pydantic.env_settings.BaseSettings.__init__
    super().__init__(
  File "pydantic\main.py", line 362, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for Config
weibo_id
  field required (type=value_error.missing)
target_group
  field required (type=value_error.missing)

**Comment by felinae98** [comment]
本项目所有功能都转到隔壁了，不要用这个项目了
